In [22]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import ast

sns.set_palette("hsv_r")

# This affects things like the size of the labels, lines, and other elements of the plot, but not the overall style. 
# The base context is “notebook”, and the other contexts are “paper”, “talk”, and “poster”, which are version of 
# the notebook parameters scaled by .8, 1.3, and 1.6, respectively.
sns.set_context("talk")

%config Inline.figure_format = 'retina'
%matplotlib inline

In [23]:
df = pd.read_csv('01_baseline_withtFB_kinematics.csv')
df

,x,y,vel_x,vel_y,vel,peak_vel,time_pv,theta_pv,dist_to_start,rt,mt,theta_end,feedback,target_x_global,target_y_global,target_angle,start_x_global,start_y_global
0,"[-0.00775,-0.00766,-0.00757,-0.00749,-0.00742,...","[19.44822,19.44799,19.44777,19.44757,19.44737,...","[0.09821,0.09208,0.086,0.07995,0.07394,0.06796...","[-0.24002,-0.22861,-0.21728,-0.20603,-0.19486,...","[0.25933,0.24646,0.23368,0.221,0.20842,0.19595...",67.408371,1.572,-1.978468,"[0.18037,0.18014,0.17991,0.1797,0.1795,0.17932...",0.759,0.190,-3.722607,1,-8.655285,24.268295,150,0.004969,19.268295
1,"[0.01471,0.01445,0.01418,0.0139,0.01363,0.0133...","[19.35508,19.35472,19.35436,19.35401,19.35365,...","[-0.26382,-0.26715,-0.27023,-0.27304,-0.2756,-...","[-0.36319,-0.3605,-0.35759,-0.35447,-0.35115,-...","[0.4489,0.4487,0.44821,0.44744,0.44639,0.44506...",72.755594,0.980,2.390779,"[0.08733,0.08694,0.08656,0.08617,0.0858,0.0854...",0.816,0.165,-24.225416,1,0.004969,29.268295,90,0.004969,19.268295
2,"[0.11099,0.11113,0.11127,0.11143,0.11159,0.111...","[19.39715,19.39728,19.3974,19.39753,19.39764,1...","[0.1339,0.14038,0.14695,0.1536,0.16033,0.16712...","[0.12965,0.12722,0.12469,0.12207,0.11936,0.116...","[0.18638,0.18945,0.19272,0.1962,0.19988,0.2037...",95.736337,0.914,1.785882,"[0.16686,0.16705,0.16724,0.16743,0.16763,0.167...",0.712,0.161,9.874702,1,10.004969,19.268295,360,0.004969,19.268295
3,"[-0.01467,-0.01472,-0.01476,-0.01481,-0.01485,...","[19.30457,19.3045,19.30443,19.30437,19.3043,19...","[-0.04957,-0.04818,-0.04683,-0.04554,-0.04431,...","[-0.0668,-0.06725,-0.06769,-0.0681,-0.0685,-0....","[0.08318,0.08273,0.08231,0.08193,0.08158,0.081...",81.462249,0.868,-2.433714,"[0.04125,0.04121,0.04117,0.04114,0.0411,0.0410...",0.720,0.146,0.328848,1,5.004968,27.928549,60,0.004969,19.268295
4,"[0.15321,0.15265,0.15209,0.15152,0.15094,0.150...","[19.40913,19.40775,19.40639,19.40503,19.40369,...","[-0.55969,-0.56299,-0.56626,-0.5695,-0.57271,-...","[-1.38671,-1.37546,-1.3639,-1.35205,-1.33993,-...","[1.4954,1.48622,1.47678,1.4671,1.45719,1.44708...",69.965199,0.982,0.574789,"[0.20448,0.20312,0.20177,0.20043,0.1991,0.1977...",0.806,0.171,-21.499604,1,8.665223,14.268295,330,0.004969,19.268295
5,"[-0.11638,-0.11646,-0.11654,-0.11661,-0.11668,...","[19.17461,19.17451,19.17441,19.17431,19.17422,...","[-0.08615,-0.08195,-0.07776,-0.07357,-0.06938,...","[-0.10234,-0.10105,-0.09989,-0.09886,-0.09798,...","[0.13377,0.1301,0.12658,0.12323,0.12006,0.1170...",63.960786,0.895,4.992677,"[0.1533,0.15343,0.15355,0.15367,0.15379,0.1539...",0.700,0.188,14.529572,1,-4.995032,27.928549,120,0.004969,19.268295
6,"[-0.03539,-0.03529,-0.03519,-0.03509,-0.03499,...","[19.38902,19.38887,19.38872,19.38857,19.38841,...","[0.10175,0.10126,0.10085,0.10054,0.10032,0.100...","[-0.14131,-0.14545,-0.14961,-0.1538,-0.15801,-...","[0.17413,0.17722,0.18043,0.18375,0.18717,0.190...",76.713216,0.884,-1.076559,"[0.12729,0.12712,0.12695,0.12677,0.12659,0.126...",0.689,0.173,11.787625,1,8.665223,24.268295,30,0.004969,19.268295
7,"[-0.08646,-0.08651,-0.08655,-0.0866,-0.08664,-...","[19.28758,19.28735,19.28712,19.28688,19.28665,...","[-0.04956,-0.0476,-0.04561,-0.04357,-0.04149,-...","[-0.23369,-0.23385,-0.23401,-0.23414,-0.23425,...","[0.23889,0.23865,0.23841,0.23816,0.2379,0.2376...",52.111584,0.969,0.396191,"[0.09344,0.09344,0.09344,0.09343,0.09343,0.093...",0.784,0.213,-9.430723,1,-8.655285,24.268295,150,0.004969,19.268295
8,"[-0.08414,-0.08433,-0.08452,-0.08472,-0.08493,...","[19.16257,19.16221,19.16185,19.1615,19.16114,1...","[-0.17906,-0.18592,-0.19289,-0.19995,-0.2071,-...","[-0.35889,-0.35887,-0.35878,-0.35863,-0.35842,...","[0.40108,0.40417,0.40735,0.41061,0.41395,0.417...",61.589194,0.925,-2.296041,"[0.13827,0.13866,0.13906,0.13946,0.13987,0.140...",0.739,0.193,-9.712271,1,8.665223,14.268295,330,0.004969,19.268295
9,"[0.20611,0.20624,0.20636,0.20648,0.20659,0.206...","[19.21805,19.21844,19.21883,19.21923,19.21962,...","[0.13328,0.1286,0.12395,0.11931,0.1147,0.11011...","[0.38938,0.3904,0.39126,0.39196,0.39251,0.3929...","[0.41156,0.41103,0.41042,0.40972,0.40892,0.408...",79.577406,0.899,-0.667627,"[0.20732,0.20735,0.20738,0.2074,0.20742,0.2074...",0.727,0.161,8.903979,1,8.665223,24.268295,30,0.004969,19.268295
10,"[0.08067,0.08042,0.08018,0.07994,0.0797,0.0794...","[19.29861,19.29837,19.29814,19.29791,19.29767,...","[-0.24734,-0.24599,-0.24454,-0.24299,-0.24134,...","[-0.23403,-0.23365,-0.23319,-0.23264,-0.23201,...","[0.3405,0.33927,0.3379,0.3364,0.33477,0.33303,...",79.856449,0.969,5.225764,"[0.08154,0.08123,0.08092,0.0806,0.08029,0.0799...",0.774,0.174,-3.973169,1,10.004969,19.268295,360,0.004969,19.268295
11,"[-0.19706,-0.19692,-0.19677,-0.19662,-0.19648,...","[19.28066,19.28047,19.28027,19.28007,19.27987,...","[0.14767,0.14728,0.14694,0.14666,0.14644,0.146...","[-0.19357,-0.19508,-0.19656,-0.19801,-0.19943,...","[0.24347,0.24444,0.24542,0.24641,0.24742,0.248...",77.469056,0.864,-1.239584,"[0.20241,0.20225,0.20209,0.20193,0.20178,0.201...",0.739,0.144,-1.479610,1,5.004968,27.928549,60,0.004969,19.268295
12,"[-0.04832,-0.04824,-0.04817,-0.04811,-0.04804,...","[19.31556,19.31527,19.31498,19.31469,19.3144,1...","[0.07564,0.0728,0.06992,0.06701,0.06406,0.0610...","[-0.28747,-0.28804,-0.28847,-0.28876,-0.28891,...","[0.29725,0.2971,0.29682,0.29643,0.29593,0.2953...",62.610845,0.955,1.789879,"[0.07122,0.07098,0.07074,0.0705,0.07026,0.0700...",0.790,0.185,-14.363371,1,0.004969,29.268295,90,0.004969,19.268295
13,"[-0.01121,-0.01123,-0.01124,-0.01126,-0.01129,...","[19.47459,19.47469,19.47478,19.47487,19.47496,...","[-0.00953,-0.01362,-0.01758,-0.02142,-0.02513,...","[0.09974,0.09712,0.09432,0.09135,0.08822,0.084...","[0.10019,0.09807,0.09595,0.09383,0.09173,0.089...",58.852958,0.929,2.166166,"[0.20693,0.20702,0.20712,0.20721,0.2073,0.2073...",0.745,0.198,3.806840,1,-4.995032,27.928549,120,0.004969,19.268295
14,"[0.01855,0.01868,0.01881,0.01894,0.01907,0.019...","[19.45152,19.45138,19.45124,19.45109,19.45095,...","[0.12793,0.12882,0.12966,0.13047,0.13122,0.131...","[-0.14136,-0.14127,-0.1412,-0.14115,-0.14111,-...","[0.19065,0.19119,0.19171,0.19221,0.1927,0.1931...",68.612466,0.925,2.211896,"[0.18373,0.18359,0.18346,0.18333,0.1832,0.1830...",0.735,0.185,-1.404384,1,10.004969,19.268295,360,0.004969,19.268295
15,"[-0.28192,-0.28213,-0.28233,-0.28252,-0.28271,...","[19.3174,19.31699,19.31659,19.3162,19.31582,19...","[-0.21109,-0.20491,-0.19883,-0.19285,-0.18698,...","[-0.41973,-0.40985,-0.39993,-0.38995,-0.37992,...","[0.46982,0.45822,0.44662,0.43503,0.42344,0.411...",55.407253,0.844,4.276477,"[0.29106,0.2912,0.29133,0.29145,0.29157,0.2916...",0.671,0.206,3.222344,1,-4.995032,27.928549,120,0.004969,19.268295

want to double check the calculations for theta_pv and theta_end 

for theta_pv: 
1. using the array 'vel' take the max value and see if that matches up with the peak_vel 
2. get the index/ distance value that the hand is at, when it is max velocity ... maybe it could work to create a seperate row for indexing (i.e. having trial numbers)
3. making sure that the peak velcity is occuring within the reach (i.e. 'dist_to_start' < 10.00 ), becuase the reach should be over when the hand is passed 10 cm 
4. determining how theta_pv is calculated and doing the calculation and checkin 

for theta_end: 
1. determining the time/sample at which we reach the endpoint (i.e. when the hand position (dist_to_start) passes 10.00)
2. use that to see what the coordinates are (x,y values)
3. calculate the real reach angle 
4. do the subtration of target angle - reach angle --> see if this is the same as theta_end

In [24]:
## convert everything to numpy arrayys 

array_cols = ['vel', 'x', 'y', 'dist_to_start']

for col in array_cols:
    df[col] = df[col].apply(
        lambda x: np.array(ast.literal_eval(x))
    )

In [29]:
## Find maximum velocity from vel --> equals peak_vel 

df['calc_peak_vel'] = df['vel'].apply(np.max)
df[['peak_vel', 'calc_peak_vel']]

     peak_vel  calc_peak_vel
0   67.408371       67.40837
1   72.755594       72.75559
2   95.736337       95.73634
3   81.462249       81.46225
4   69.965199       69.96520
5   63.960786       63.96079
6   76.713216       76.71322
7   52.111584       52.11158
8   61.589194       61.58919
9   79.577406       79.57741
10  79.856449       79.85645
11  77.469056       77.46906
12  62.610845       62.61084
13  58.852958       58.85296
14  68.612466       68.61247
15  55.407253       55.40725

In [30]:
## Find index where peak velocity occurs